name: travel_guide
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  animated_notch_bottom_bar: ^1.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  comment_tree: ^0.3.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dartz: ^0.10.1
  dio: ^5.2.1+1
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localization: ^0.1.12
  flutter_spinkit: ^5.2.0
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  google_maps_flutter: ^2.4.0
  image_picker: ^1.0.2
  like_button: ^2.0.5
  loader_overlay: ^2.2.0
  modal_bottom_sheet: ^2.1.2
  pretty_dio_logger: ^1.3.1
  responsive_sizer: ^3.1.1
  shared_preferences: ^2.0.17
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  location: ^5.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_chat_ui: ^1.6.9
  uuid: ^3.0.7
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
flutter_assets:
  assets_path: asset/images/
  output_path: lib/core/constants/
  filename: app_images.dart
  field_prefix: null

flutter:

  uses-material-design: true

  assets:
    - lang/
    - asset/images/user_avatar/
    - asset/images/user_avatar/user_avatar_image.png
    - asset/images/
  fonts:
    - family: DMSans-Bold
      fonts:
        - asset: asset/fonts/IndieFlower-Regular.ttf
    - family: Kalam
      fonts:
        - asset: asset/fonts/Kalam-Regular.ttf
    - family: JosefinSans
      fonts:
        - asset: asset/fonts/JosefinSans-VariableFont_wght.ttf
  #     - family: DMSans-Medium
  #       fonts:
  #         - asset: asset/fonts/DMSans-Medium.ttf
  #     - family: DMSans-Regular
  #       fonts:
  #         - asset: asset/fonts/DMSans-Regular.ttf
