name: travel_guide
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  curved_navigation_bar: ^1.0.3
  responsive_sizer: ^3.1.1
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.17
  flutter_localization: ^0.1.12
  get_it: ^7.6.0
  fluro: ^2.0.5
  comment_tree: ^0.3.0
  dio: ^5.2.1+1
  sqflite: ^2.2.8+4
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1
  fluttertoast: ^8.2.2
  loader_overlay: ^2.2.0
  flutter_spinkit: ^5.2.0
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.4.0

flutter_assets:
  assets_path: asset/images/
  output_path: lib/core/constants/
  filename: app_images.dart
  field_prefix: null

flutter:

  uses-material-design: true

  assets:
    - lang/
    - asset/images/user_avatar/
    - asset/images/
  fonts:
    - family: DMSans-Bold
      fonts:
        - asset: asset/fonts/DMSans-Bold.ttf
#     - family: DMSans-MediumItalic
#       fonts:
#         - asset: asset/fonts/SDMSans-MediumItalic.ttf
#     - family: DMSans-Medium
#       fonts:
#         - asset: asset/fonts/DMSans-Medium.ttf
#     - family: DMSans-Regular
#       fonts:
#         - asset: asset/fonts/DMSans-Regular.ttf


